GET http://localhost:8080/users

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "namauser": "shella.vidya",
    "password": "123"
}

###
GET http://localhost:8080/dtkaryawan/202

###
GET http://localhost:8080/departemen/D020

###
GET http://localhost:8080/dataKaryawan
###
GET http://localhost:8080/dataKaryawan/202

###
GET http://localhost:8080/lapHarian/202

###
GET http://localhost:8080/lapHarianById/0000000202_2023-03-27

###
GET http://localhost:8080/laporanHarian/0000000202_2023-03-28

###
DELETE  http://localhost:8080/delLaporanHarianById/0000000202_2023-03-27